import Head from 'next/head';
import '@styles/globals.scss';
import '@styles/stisla/components.css';
import '@styles/stisla/style.css';

function MyApp({ Component, pageProps } : any): JSX.Element {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
